# Generated by Django 4.2.27 on 2026-01-19 05:03

from django.db import migrations, models
import employees.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_email_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', validators=[employees.validators.validate_jpg_image]),
        ),
    ]
